[release] a version can run get_put workload correctly.
* Update README.md

* Update README.md

* [feat] Add workload module dir

* [feat] Add workload module dir

* [feat] implement trace_replay

trace_replay read a workload trace using jsonCPP.

* [feat] add DMM_Trie header file

* [feat] implement LSVPS

* [feat] implement DMM Trie

* [feat] implement VDLS

* [fix] fix some syntax errors

* [test] complete trace_replay.cpp

* [feat] LSVPS: finish page replay process using update() interface in DMMTrie.hpp

* [feat] DMMTrie:

set active delta page and provide an interface for LSVPS
add DeltaPage class, pass unserialized DeltaPage to LSVPS
add update interface in BasePage class
change BasePage::DeserializeFrom to BasePage construction function

* [fix] remove .vscode/

* [test] get put test

* [feat] LSVPS: Handle active delta page versions in ApplyDelta

- Add version check to skip delta items beyond requested version
- Optimize delta application for active delta pages by breaking early

* [feat] LSVPS: store index files in 'IndexFile' directory

* [feat] DMM_Trie:
add deserialize function in DeltaPage class
modify UpdateDeltaItem and GetLatestBasePageKey functions

* [merge]

* [fix] fix some syntax errors

* [fix] fix DMMTrie::UpdatePage bug

* [fix] remove aux_source_directory in CMakeLists.txt

* [merge] merge DMM_Trie into dev

* [fix] add simple in CMakeLists.txt

* [fix] fix key name format

* [fix] make cmake debug-able

* [style] rename a few functions to follow Google Style Guides

* [chore] remove generated files and IDE settings

* [feat] LSVPS: handle initial basepage creation

When LSVPS hasn't received any basepage for a pid yet, create a new
basepage instance instead of returning null. This handles the
initialization phase where no basepage has been stored in LSVPS.

* [fix] add OpenSSL to cmake

* [merge] merge dev -> xinyu.chen

* [merge] merge xinyu.chen into dev (#7)

* [fix] remove aux_source_directory in CMakeLists.txt

* [fix] add simple in CMakeLists.txt

* [fix] fix key name format

* [fix] make cmake debug-able

* [fix] add OpenSSL to cmake

* [merge] merge dev -> xinyu.chen

---------

Co-authored-by: xinyu.chen <xinyu.chen@zju.com>

* [refactor] separate class LSVPS declaration and implementation

* [fix] fix DMMTrie: PageKey confrontation in LRU cache

* [feat] separate DMMTrie.cpp and DMMTrie.hpp

* [fix] fix DMMTrie: PageKey confrontation in LRU cache

* [fix] fix DMMTrie: PageKey confrontation in LRU cache

* [fix] fix DMMTrie: PageKey confrontation in LRU cache

* [fix] fix cmake bugs

* [merge] handle 500 gets and puts (#8)

* [fix] fix DMMTrie: PageKey confrontation in LRU cache

* [feat] separate DMMTrie.cpp and DMMTrie.hpp

* [fix] fix DMMTrie: PageKey confrontation in LRU cache

* [fix] fix DMMTrie: PageKey confrontation in LRU cache

* [fix] fix DMMTrie: PageKey confrontation in LRU cache

* [fix] fix cmake bugs

---------

Co-authored-by: 钱于飞 <3200102544@zju.edu.cn>

* [feat] add go interface

add main.go

* [release] run 500 gets and puts

* [release] run 500 gets and puts

key length = 5
value length = 256

* [release] run 5000 gets and puts

key length = 5
value length = 256

* [feat] add go interface

error: undefined reference to

* [feat] add go interface

successfully run Get and Put

* [feat] add go interface

successfully run Get and Put

* [feat] add go interface

successfully test multiple go files

* [feat] add go interface

successfully test get and put

* [doc] add db-interface.md

* [feat] add go interface

[incomplete] implement the NewBatch interface

* [feat] add go interface

implement NewBatch interface

* [fix] fix some bugs

* [feat] add experiment result ploting

* [test] add result plotting for get_put

* [test] add result plotting for get_put

* [fix] LSVPS: correct deltapage lookup in memory buffer

Fix a bug where deltapage required for replay could not be correctly
located in the memory buffer. This ensures proper page version reconstruction
during page replay.

* [fix] each kv is assigned a unique version

* [fix] each kv is assigned a unique version

* [fix] clear data dir for each test

* [fix] fix some bugs in serialization and deserialization
DMMTrie: fix se and deserialization of IndexNode
LSVPS: fix the LookupBlock size to 4KiB

* [fix] fix some errors:
DMMTrie: Get function produce error when getting early versions
DMMTrie: Put function temporarily store basepage and deltapage until deltapage pass them to LSVPS

* [fix] DMMTrie: fix some syntax errors

* [fix]: DMMTrie: fix error in Get and GetProof function

* [feat] DMMTrie: Commit function handle put in batch

* [fix] fix some bugs in retrieving the smallest DeltaPage with a version bigger than the requested version

* [fix] LSVPS: fix some syntax errors

* [fix] DMMTrie: fix some bugs in traversing the nibble path

* [chore] remove asan_log.txt from remote repository

* [feat] add get_put_2 to support historical queries

* [merge] merge into dev from xinyu.chen

* [fix] remove aux_source_directory in CMakeLists.txt

* [fix] add simple in CMakeLists.txt

* [fix] fix key name format

* [fix] make cmake debug-able

* [fix] add OpenSSL to cmake

* [merge] merge dev -> xinyu.chen

* [feat] add go interface

add main.go

* [feat] add go interface

error: undefined reference to

* [feat] add go interface

successfully run Get and Put

* [feat] add go interface

successfully run Get and Put

* [feat] add go interface

successfully test multiple go files

* [feat] add go interface

successfully test get and put

* [doc] add db-interface.md

* [feat] add go interface

[incomplete] implement the NewBatch interface

* [feat] add go interface

implement NewBatch interface

* [feat] add experiment result ploting

* [test] add result plotting for get_put

* [test] add result plotting for get_put

* [fix] each kv is assigned a unique version

* [fix] each kv is assigned a unique version

* [feat] add get_put_2 to support historical queries

---------

Co-authored-by: xinyu.chen <xinyu.chen@zju.com>

* [refactor] LSVPS: change LoadPage return type from Page* to BasePage*

* [chore] rename utils.h to commen.h

* [feat] add commit interface in gowrapper

* [fix] DMMTrie: add deep copy construtor of BasePage, DeltaPage and IndexNode

* [fix] LSVPS: add deep copy when creating BasePage in LoadPage

* [fix] some sanitize

* [test] test get_put

* [fix] LSVPS: fix serialization/deserialization bugs by removing sizeof(PageKey)

* [merge] xinyu.chen <- dev

* [doc] add the notice of changing data_path

* [fix] LSVPS: correct PageKey comparison in lookup_block binary search

The previous implementation incorrectly compared both PageKey and location
when performing binary search in lookup_block entries. This caused incorrect
page lookups as the location value should not affect the search order.

* [fix] LSVPS: correct the initialization condition of the recusive call in readPageFromIndexFile

* [test] test result plotting

* [chore] rename commen.hpp to common.hpp

* [revert] restore DMMTrie.cpp to previous commit due to incorrect merge

* [feat] DMMTrie: maintain the versions of deltapage for every pid to accelerate deltapage searching in PageReplay

* [merge] merge DMM_Trie to dev

* [fix] LSVPS: fix the replay deltapage search using the deltapage version maintained by the DMM trie

* [build] add debug and release mode support
- Add build type selection (debug/release) in build.sh
- Add runtime mode selection in run.sh
- Enable ASAN and logging for debug mode
- Add colored output for better visibility

* [test] draw result plot

* [test] add wrong count as a metric

* [feat] LSVPS: add a parameter for LSVPS constructor to indicate the IndexFile/ location.

* [build] correct build scripts

* [fix] add directories into run.sh

* [merge] merge xinyu.chen into dev

* [fix] remove aux_source_directory in CMakeLists.txt

* [fix] add simple in CMakeLists.txt

* [fix] fix key name format

* [fix] make cmake debug-able

* [fix] add OpenSSL to cmake

* [merge] merge dev -> xinyu.chen

* [feat] add go interface

add main.go

* [release] run 500 gets and puts

* [release] run 500 gets and puts

key length = 5
value length = 256

* [release] run 5000 gets and puts

key length = 5
value length = 256

* [feat] add go interface

error: undefined reference to

* [feat] add go interface

successfully run Get and Put

* [feat] add go interface

successfully run Get and Put

* [feat] add go interface

successfully test multiple go files

* [feat] add go interface

successfully test get and put

* [doc] add db-interface.md

* [feat] add go interface

[incomplete] implement the NewBatch interface

* [feat] add go interface

implement NewBatch interface

* [feat] add experiment result ploting

* [test] add result plotting for get_put

* [test] add result plotting for get_put

* [fix] each kv is assigned a unique version

* [fix] each kv is assigned a unique version

* [fix] clear data dir for each test

* [feat] add get_put_2 to support historical queries

* [feat] add commit interface in gowrapper

* [fix] some sanitize

* [test] test get_put

* [merge] xinyu.chen <- dev

* [doc] add the notice of changing data_path

* [test] test result plotting

* [test] draw result plot

* [test] add wrong count as a metric

* [fix] add directories into run.sh

---------

Co-authored-by: xinyu.chen <xinyu.chen@zju.com>

* [release] run get_put correctly.

---------

Co-authored-by: self-consstency <dezhi2002@outlook.com>
Co-authored-by: xinyu.chen <xinyu.chen@zju.com>
Co-authored-by: 钱于飞 <3200102544@zju.edu.cn>